try {
    hi
} catch (error) {
    console.log(error);
}